### ISSUE TITLE
Eindeutige URLs verwenden

### ISSUE THREAD

**Issue by mario-zelger** [scout-ch/hering#27]
Im Moment werden die URLs von `sections` auf Basis des `slug`s abgeleitet. Die Eindeutigkeit basiert somit grundsätzlich auf dem Bereich / Kapitel. Wird dieser `slug` angepasst so ist die bisherige URL nicht mehr gültig.

Aufgrund der Übersetzungen sind die URLs zudem sprach**ab**hängig. Das Potenzial für ungültige Links steigt damit noch zusätzlich. Hier ein Beipsiel eines einzelnen Kapitels.

* DE: `https://scout-ch.github.io/hering/#/Vorbereitung%23Lagerdaten`
* FR: `https://scout-ch.github.io/hering/#/Preparation%23Donnees-relatives-aux-camps`
* IT: `https://scout-ch.github.io/hering/#/Preparazione%23Dati-del-campo`

Das aktuelle API liefert pro Bereich und Kapitel eindeutige, nummerische Ids. Diese könnten anstelle der `slug`s in die URL eingebaut werden. Das Format wäre dann `/hering-root/#/:sectionId%23:chapterId`.

**Beispiel**

```yaml
[
    {
        "id": 1,
        "title": "Bereich 1",
        # ... mehr Daten
        "chapters": [
            {
                "id": 1,
                "title": "Kapitel 1",
                # ... mehr Daten
            },
            {
                "id": 2,
                "title": "Kapitel 2",
                # ... mehr Daten
            },
            # ... mehr Daten
    },
    # ... mehr Daten
]
```

URL aktuell: `https://scout-ch.github.io/hering/#/Bereich-1%23Kapitel-1`
URL neu: `https://scout-ch.github.io/hering/#/1%231`

Wenn #26 umgesetzt ist würde die neue URL `https://hering.scout.ch/1#1` lauten. Eine sprachunabhängige URL würde zudem bei der Umsetzung von #10 helfen.
